---
- name: copy etcd.conf to `/etc/etcd`
  template:
    src: etcd.conf
    dest: /etc/etcd/etcd.conf
    owner: root
    group: root
    mode: 0755
  tags:
    - etcd
    - etcd_conf

- name: copy etcd.service to `/lib/systemd/system`
  template:
    src: etcd.service
    dest: /lib/systemd/system/etcd.service
    owner: root
    group: root
    mode: 0755
  tags:
    - etcd
    - etcd_conf

- name: create `/var/lib/etcd` directory
  file:
    path: /var/lib/etcd
    state: directory
    owner: etcd
    group: etcd
    mode: 0755
  tags:
    - etcd
    - etcd_conf

- name: chown -r `/etc/etcd` directory owner to ectd
  file:
    path: /etc/etcd
    state: directory
    owner: etcd
    group: etcd
    mode: 0755
    recurse: yes
  tags:
    - etcd
    - etcd_conf

- name: start etcd
  service:
    name: etcd
    state: started
    enabled: yes
  tags:
    - etcd
    - etcd_conf
    - etcd_start

- name: restart etcd
  service:
    name: etcd
    state: restarted
  tags:
    - etcd
    - etcd_conf
    - etcd_restart
