---
kube_url: https://storage.googleapis.com/kubernetes-release/release/v1.8.2/bin/linux/amd64
cni_url: https://github.com/containernetworking/plugins/releases/download
cni_version: "v0.6.0"
cni_base_file_path: "cni-plugins-amd64-v0.6.0"
kube_apiserver: https://172.16.35.12:6443
bootstrap_token: cec950dd20e76e1a8500b6cdab274c1d
master_node_hostname: master1
encryption_secret: SUpbL4juUYyvxj3/gonV5xVEx8j769/99TSAf8YT/sQ=
