---
- name: copy manager-csr.json to `/etc/kubernetes/pki`
  template:
    src: manager-csr.json
    dest: /etc/kubernetes/pki/manager-csr.json
    owner: root
    group: root
    mode: 0755
  tags:
    - k8s
    - k8s_install
    - k8s_controller_manager_certificates

- name: create kube-controller-manager certificate
  shell: |
    cfssl gencert \
      -ca=ca.pem \
      -ca-key=ca-key.pem \
      -config=ca-config.json \
      -profile=kubernetes \
      manager-csr.json | cfssljson -bare controller-manager
  args:
    chdir: /etc/kubernetes/pki
  tags:
    - k8s
    - k8s_install
    - k8s_controller_manager_certificates
