---
- name: copy kubelet-csr.json to `/etc/kubernetes/pki`
  template:
    src: kubelet-csr.json.j2
    dest: /etc/kubernetes/pki/kubelet-csr.json
    owner: root
    group: root
    mode: 0755
  tags:
    - k8s
    - k8s_install
    - k8s_kubelet_certificates

- name: create master node certificate
  shell: |
    cfssl gencert \
      -ca=ca.pem \
      -ca-key=ca-key.pem \
      -config=ca-config.json \
      -hostname=master1,172.16.35.12 \
      -profile=kubernetes \
      kubelet-csr.json | cfssljson -bare kubelet
  args:
    chdir: /etc/kubernetes/pki
  tags:
    - k8s
    - k8s_install
    - k8s_kubelet_certificates
