---
- name: openssl genrsa sa.key
  shell: |
    openssl genrsa -out sa.key 2048
    openssl rsa -in sa.key -pubout -out sa.pub
  args:
    chdir: /etc/kubernetes/pki
  tags:
    - k8s
    - k8s_install
    - k8s_service_account_key

