---
- name: install kubelet kubeadm kubectl
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
    enablerepo: kubernetes
  with_items:
    - kubelet
    - kubeadm
    - kubectl
  tags:
    - kube

- name: set kubelet service to enabled
  service:
    name: kubelet
    enabled: yes
  tags:
    - kube
