---
- name: add kubernetes.repo
  template:
    src: kubernetes.repo
    dest: //etc/yum.repos.d/kubernetes.repo
    owner: root
    group: root
    mode: 0755
  tags:
    - kube

- name: import rpm key
  rpm_key:
    key: "{{ item }}"
    state: present
  with_items:
    - https://packages.cloud.google.com/yum/doc/yum-key.gpg
    - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
  tags:
    - kube
